# Kali Linux Dev Container
FROM kalilinux/kali-rolling

RUN apt update && \
    apt install -y \
    nmap \
    metasploit-framework \
    net-tools \
    curl \
    git \
    python3 \
    python3-pip

CMD [ "bash" ]
